#!/usr/bin/env bash
# This script checks if the host is on the network by pinging the specified IP address.

if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit
fi
ping -c 5 "$1"